### ISSUE TITLE
Error: Failed to read imagedata from dataurl

### ISSUE THREAD

**Issue by MattiHay** [blinkmobile/cordova-plugin-sketch#10]
Hello,

tried your nice plugin for making annotations on fotos and images.
My app reads image data from a backend as base64 with the special dataurl-format for jpegs dataurls.
Works fine so far :-)
But when i take a picture from camera or foto-lib (taken by cordova plugins) i can visualize them in my app (my image-tags also work with data-url as src-attribute for images). but i cant use the plugin because i always get the error messagew "Failed to read imagedata from dataurl". 
Any ideas?
Testing on iPad4, iOS 10.3.3

kind regards
Matthias

**Comment by mymattcarroll** [comment]
@mcdroemmel , thank you for reporting this issue.

This repo is part of our legacy code base and is no longer supported/maintained by us. You are welcome to create/publish a fork to npm or do what you want with the code.

Apologies for any inconvenience.
