### ISSUE TITLE
Error: JavaBinder: !!! FAILED BINDER TRANSACTION !!!

### ISSUE THREAD

**Issue by GopalanHarish** [blinkmobile/cordova-plugin-sketch#13]
Hello, 
First off, great plugin!
but I seem to have a problem when I work with high quality image.
Cant this be fixed?

Error from logcat:

> 08-08 11:15:53.775 28518 28518 E JavaBinder: !!! FAILED BINDER TRANSACTION !!!
> (parcel size = 1401464)
> 08-08 11:15:53.777 28518 28518 E AndroidRuntime: FATAL EXCEPTION: main
> 08-08 11:15:53.777 28518 28518 E AndroidRuntime: Process: io.cordova.hellocordov
> a, PID: 28518
> 08-08 11:15:53.777 28518 28518 E AndroidRuntime: java.lang.RuntimeException: Fai
> lure from system

**Comment by mymattcarroll** [comment]
@wenn32, thank you for reporting this issue.

This repo is part of our legacy code base and is no longer supported/maintained by us. You are welcome to create/publish a fork to npm or do what you want with the code.

Apologies for any inconvenience.

**Comment by GopalanHarish** [comment]
thanks for letting me know. Cheers! :)
