### ISSUE TITLE
Any plan to support Windows 10?

### ISSUE THREAD

**Issue by fsundjaja** [blinkmobile/cordova-plugin-sketch#14]
We really like this sketch plugin. However we notice it keeps crashing on Win 10. Any ideas on how to fix it? Or do any plan for Win 10 support.

**Comment by mymattcarroll** [comment]
@fsundjaja, thank you for reporting this issue.

This repo is part of our legacy code base and is no longer supported/maintained by us. You are welcome to create/publish a fork to npm or do what you want with the code.

Apologies for any inconvenience.
