### ISSUE TITLE
Unable to use FILE_URI as background

### ISSUE THREAD

**Issue by beard7** [blinkmobile/cordova-plugin-sketch#15]
I realise that this plugin is no loner supported/maintained by the developer, but there is clearly an existing user base that may be able to help with issues.

I'm trying to use a FILE_URI as inputType and I'm passing the `image.src` as inputData, like this:
````
        var image = document.getElementById('my-image');
        navigator.sketch.getSketch(onSuccess, onFail, {
            destinationType: navigator.sketch.DestinationType.DATA_URL,
            encodingType: navigator.sketch.EncodingType.JPEG,
            inputType: navigator.sketch.InputType.FILE_URI,
            inputData: image.src
        });
````
The path to the image with id my-image is valid and the image is displayed. However, when calling `getSketch` I get an error: `Failed to generate sketch. File not found: /android_asset/www/img/image.jpg`

If it makes any difference, this is using Cordova Android platform version 7.1

Any suggestions? Thanks

**Comment by mymattcarroll** [comment]
@beard7, thank you for reporting this issue.

This repo is part of our legacy code base and is no longer supported/maintained by us. You are welcome to create/publish a fork to npm or do what you want with the code.

Apologies for any inconvenience.
