### ISSUE TITLE
App crashes when starting on iOS

### ISSUE THREAD

**Issue by MattiHay** [blinkmobile/cordova-plugin-sketch#16]
App crashes when starting on iOS.
Using iOS 12. Build on Phonegap with cli-8.0.0.

**Comment by mymattcarroll** [comment]
@mcdroemmel, thank you for reporting this issue.

This repo is part of our legacy code base and is no longer supported/maintained by us. You are welcome to create/publish a fork to npm or do what you want with the code.

Apologies for any inconvenience.
