### ISSUE TITLE
Poor quality of images on android

### ISSUE THREAD

**Issue by vilhelmjosander** [blinkmobile/cordova-plugin-sketch#3]
Hi,

I'm using this in combination with the cordova-plugin-camera plugin. First, the user takes a picture like this:

``` javascript
navigator.camera.getPicture(onSuccess, onFail, {
          quality: 100,
          destinationType: allowAnnotation ? Camera.DestinationType.FILE_URI : Camera.DestinationType.DATA_URL,
          targetWidth: 1600,
          targetHeight: 1600,
          correctOrientation: true
      });
```

I then send the fileUri to sketch like this:

``` javascript
navigator.sketch.getSketch(onSketchSuccess, onSketchError, {
        destinationType: navigator.sketch.DestinationType.DATA_URL,
        inputType : navigator.sketch.InputType.FILE_URI,
        encodingType: navigator.sketch.EncodingType.JPEG,
        inputData : fileUriFromCamera
      });
```

The output from sketch seems like it's really compressed though when using the destinationType navigator.sketch.DestinationType.DATA_URL. 

The quality of the image is really poor, even if I'm not actually drawing anything. Noticeably poorer quality than using destinationType Camera.DestinationType.DATA_URL with only the cordova-plugin-camera.

I've tried using both PNG and JPEG with the same result. Any idea on how to solve this? Great plugin otherwise!

**Comment by jokeyrhyme** [comment]
@vilhelmjosander thanks for bringing this to our attention. :)

We'll allocate some resources to this issue when appropriate, but feel free to submit a PR in the meantime if you get impatient. Cheers!

**Comment by vilhelmjosander** [comment]
@jokeyrhyme Ok great, thanks! Any ETA from your side? I could look into it but don't have that much time the coming weeks.

**Comment by brunolanevik** [comment]
Any progress on this? I have the same issue.

My guess is that there seems do be some downscaling from the original image size when you finish drawing.

**Comment by pbergner** [comment]
also seeing this, any update?

**Comment by jokeyrhyme** [comment]
I'm fairly certain the issue can be solved by making changes within this file:

https://github.com/blinkmobile/cordova-plugin-sketch/blob/master/src/android/TouchDrawActivity.java

A quick look would indicate that we can use some of the Android built-ins to achieve better scaling:

https://stackoverflow.com/questions/4207562/android-high-quality-image-resizing-scaling

https://stackoverflow.com/questions/24745147/java-resize-image-without-losing-quality

https://stackoverflow.com/questions/16465686/android-resizing-bitmaps-without-losing-quality

We can't make any guarantees about when we can get some dedicated office time on this issue, but we'd certainly accept a PR that makes the required tweaks

**Comment by pbergner** [comment]
Thanks for the guidance @jokeyrhyme. Unfortunately I wasn't able to get it working but I'm pretty inexperienced.  My issue is specifically around multiple edits degrading the quality but I'm starting to think that's just a fundamental issue with using JPEGs and recompressing multiple times.

**Comment by MatthewKapteyn** [comment]
Image quality is so poor on android because of the way Intent is used to pass back image data. Android limits the size of this to 1MB. This is why the image passed back is shrunk down with a very small scale of 35% (see mscale variable). This works in most cases but not always guaranteed to shrink the image below 1MB. Need to avoid such drastic downsizing and write to file instead.

**Comment by MatthewKapteyn** [comment]
Just adding a note here for anybody looking. My fork includes a fix for this. 

[https://github.com/MatthewKapteyn/cordova-plugin-sketch](https://github.com/MatthewKapteyn/cordova-plugin-sketch)

**Comment by mymattcarroll** [comment]
@vilhelmjosander, thank you for reporting this issue.

This repo is part of our legacy code base and is no longer supported/maintained by us. You are welcome to create/publish a fork to npm or do what you want with the code.

Apologies for any inconvenience.

**Comment by maurotrigo** [comment]
Thanks a lot @MatthewKapteyn !

**Comment by fpardigon** [comment]
@MatthewKapteyn I always have a bad quality on android, the image goes from 150ko to 50ko, you have an idea?
