### ISSUE TITLE
Change name button

### ISSUE THREAD

**Issue by DanielMutu** [blinkmobile/cordova-plugin-sketch#6]
Hi, How i can change name buttons, for example: done, cancel, erase ecc ?
Thanks, for great plugin!

**Comment by mymattcarroll** [comment]
@DanielMutu, Thank you for reporting this issue.

This repo is part of our legacy code base and is no longer supported/maintained by us. You are welcome to create/publish a fork to npm or do what you want with the code.

Apologies for any inconvenience.
