### ISSUE TITLE
Windows 10 support

### ISSUE THREAD

**Issue by morwoen** [blinkmobile/cordova-plugin-sketch#8]
The windows implementation currently uses functions which are not present in windows after 8.1. One such function is `execUnsafeLocalFunction`, but I think there was something else as well.

Here is a link to SO with the aforementioned func: https://stackoverflow.com/questions/32059361/msapp-execunsafelocalfunction-does-not-appear-to-be-in-windows-10-what-replaces

Is there a way to support both win8.1 and 10 (check for which is the current version or smth)? If not, do you want to keep support for 8.1 at all? Should you just tag the current as win8.1 support and put win10 support in master?

**Comment by mymattcarroll** [comment]
@morwoen, Thank you for reporting this issue.

This repo is part of our legacy code base and is no longer supported/maintained by us. You are welcome to create/publish a fork to npm or do what you want with the code.

Apologies for any inconvenience.

**Comment by morwoen** [comment]
@mymattcarroll, thanks a lot for the reply. Do you know if there is a maintained repo?

**Comment by mymattcarroll** [comment]
Sorry to say, I cannot.

A few forks have been made and it seems this one has been updated most recently: 
https://github.com/Xakal7/cordova-plugin-sketch

Good luck. :)
