### ISSUE TITLE
Not able to use the plugin on IPad IOS 10

### ISSUE THREAD

**Issue by tushaagit** [blinkmobile/cordova-plugin-sketch#9]
Getting error while using this plugin on Ipad IOS 10.  TypeError: undefined is not an object (evaluating 'navigator.sketch.getSketch').  Same plugin works on for android devices. Please suggest the solution.

**Comment by mymattcarroll** [comment]
@tushaagit, Thank you for reporting this issue.

This repo is part of our legacy code base and is no longer supported/maintained by us. You are welcome to create/publish a fork to npm or do what you want with the code.

Apologies for any inconvenience.
